# Generated by Django 4.1.1 on 2022-11-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
            ],
        ),
    ]
